version: "3.7"
services:
  # RabbitMQ Service (1 instance)
  rabbitmq:
    image: "rabbitmq:alpine"
    container_name: rabbitmq
    ports:
      - "5672:5672"   # AMQP port
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    # networks:
    #   - rabbitmq-net
    restart: always

  # Application microservice
  application:
    build: ./application
    container_name: application
    env_file:
      - ./application/.env.dev
    depends_on:
      - database
      - rabbitmq 
    ports:
      - "8001:8001"
    # networks:
    #   - rabbitmq-net
    volumes:
      - .:/app/
      - /app/application/node_modules
    restart: always

    # Traefik (Optional, for routing traffic to the Node.js applications)
  # traefik:
  #   image: "traefik:v2.10"
  #   container_name: traefik
  #   command:
  #     - "--api.insecure=true"  # Enable web UI
  #     - "--providers.docker=true"  # Enable Docker provider
  #     - "--entryPoints.web.address=:80"  # HTTP Entry point
  #   ports:
  #     - "80:80"      # HTTP
  #     - "8080:8080"  # Traefik Dashboard
  #   networks:
  #     - rabbitmq-net
  #   volumes:
  #     - "/var/run/docker.sock:/var/run/docker.sock"
  #   restart: always
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 6543:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=innostax_boilerplate
    volumes:
      - pgdata:/data/postgres
    
  migrate:
    build: ./database
    container_name: migrate
    env_file:
      - ./database/.env.dev
    depends_on:
      - database
    # networks:
    #   - rabbitmq-net
    volumes:
      - .:/app/
      - /app/database/node_modules

  nginx-proxy:
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - application
    ports:
      - 80:80

# networks:
#   rabbitmq-net:
#     driver: bridge

volumes:
  rabbitmq-data:
  pgdata:
    driver: local